### ISSUE TITLE
need loading state on magic link login button

### ISSUE THREAD

**Issue by youngbloodcyb** [9d8dev/router#15]
There's currently no loading state on the magic link auth button. It's easy to click it multiple times which will lead to sending multiple emails for authentication

<img width="950" alt="Screenshot 2024-09-08 at 5 50 20 PM" src="https://github.com/user-attachments/assets/e2351c9d-69f8-476b-ada6-54f5d7b61166">

**Comment by vtfg** [comment]
I will do it.

**Comment by youngbloodcyb** [comment]
@vtfg just assigned! Thanks for taking this on
