### ISSUE TITLE
Add an Alternative to Resend for Email Services

### ISSUE THREAD

**Issue by adryserage** [9d8dev/router#30]
**Description:** 

Currently, we rely on Resend for email services in our project. However, adding an alternative email service provider would offer redundancy and flexibility. Having a fallback email solution is crucial for maintaining consistent communication with users, especially in cases where Resend might face service disruptions or if we encounter integration challenges.

**Proposed Solution:**

- Research and evaluate viable alternatives (e.g., SendGrid, Amazon SES, Mailgun or SMTP and Node mailer).
- Implement a switch or a configuration option to easily toggle between Resend and the alternative provider.
- Document the setup and configuration of the new provider to ensure seamless integration and usage.

**Benefits:**

- Improved reliability with a backup email service.
- Enhanced flexibility to adapt to future scaling or feature requirements.
- Better risk management and continuity of email communications.

**Potential Challenges:**

- Integration effort and initial setup time.
- Maintaining compatibility with current email functionalities.

**Comment by youngbloodcyb** [comment]
We're going to stick with Resend for sake of simplicity. There's definitely potential to add other email providers but this is pretty easy and can be done in a fork of the repo or in a local clone of the repo. There are other things in the project that we are opting to focus on that relate to the core functionality of the app.
